version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: userTest
      POSTGRES_PASSWORD: passwordTest
      POSTGRES_DB: databaseTest
    ports:
      - "5432:5432"
  frontend:
    build: 
      context: ./frontend
      args:
        PORT: "3000"
    ports: 
      - "3001:3000"
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
      args:
        PORT: "5005"
    ports:
      - "3002:5005" 
    environment:
      PORT: 5005
    depends_on:
      - db