version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: userTest
      POSTGRES_PASSWORD: passwordTest
      POSTGRES_DB: databaseTest
    ports:
      - "4444:5432"

  frontend:
    build: 
      context: ./frontend
      args:
        PORT: "3000"
    ports: 
      - "3001:3000"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      args:
        PORT: "5005"
    ports:
      - "3002:5005" 
    environment:
      PORT: 5005
      DB_HOST: db
      DB_USER: userTest
      DB_PASSWORD: passwordTest
      DB_NAME: databaseTest
    depends_on:
      - db