name: MAIN #naming

on: [push] #method of running

jobs: 
  build: #jobs naming
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a on-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other sections to build,
          echo test, and deploy your project.